version: "3"
services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - pgs_data:/var/lib/postgresql/data
    env_file:
      - .env/.postgres.env
    ports:
      - 5432:5432
  api:
      image: instagramtools/api
      depends_on:
        - postgres
      links:
        - postgres:postgres
      environment:
        - DEBUG=False
        - DB_SERVICE=postgres
        - DB_PORT=5432
      env_file:
      - .env/.postgres.env
      - .env/.api.env
      - .env/.mail.env
  manager:
    image: instagramtools/manager
    command: sh wait-for.sh http://api:8000 sh start.sh 8765
    depends_on:
      - postgres
      - api
    links:
      - postgres:postgres
      - api:api
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - APP_BOT_GATEWAY=http://manager:8765
      - P_USER=ec2-user
    env_file:
    - .env/.postgres.env
    - .env/.api.env
    - .env/.manager.env
    - .env/.bot-manager.env

  nginx:
    image: instagramtools/user-interface
    ports:
     - "80:80"
     - "443:443"
    environment:
     - DEBUG=off
    env_file:
     - .env/.nginx.env
    depends_on:
    - api
    - payment-manager
    - manager
    links:
    - api:api
    - payment-manager:payment-manager
    - manager:manager

  payment-manager:
    image: instagramtools/payment-manager
    depends_on:
    - postgres
    - api
    links:
    - postgres:postgres
    - api:api
    ports:
    - "7000:7000"
    environment:
    - DEBUG=False
    - DB_SERVICE=postgres
    - DB_PORT=5432
    env_file:
    - .env/.payment-manager.env
    - .env/.postgres.env

  mailserver:
    image: gott50/mailserver
    ports:
    - "7070:7070"
    environment:
    - DEBUG=False
    env_file:
    - .env/.mail.env

volumes:
  pgs_data: