version: "3"
services:
  postgres:
    image: postgres:10.5-alpine
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env/.postgres.env
  api:
      image: instagramtools/api
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      links:
        - postgres:postgres
      environment:
        - DEBUG=False
        - DB_SERVICE=postgres
        - DB_PORT=5432
      env_file:
      - .env/.postgres.env
      - .env/.api.env
  manager:
    image: instagramtools/manager
    command: sh wait-for.sh http://api:8000 python start.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - api
    links:
      - postgres:postgres
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
    env_file:
    - .env/.postgres.env
    - .env/.api.env
    - .env/.manager.env

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 128M

  nginx:
     image: instagramtools/user-interface
     ports:
       - "80:80"
       - "443:443"
     environment:
       - DEBUG=off
     env_file:
       - .env/.nginx.env

volumes:
  db_data:
  log_data: