version: "2"
services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g

  web:
    command: ["sh", "./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_quickstart.py"]
    image: instagramtools/web
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - selenium
      - proxy-manager
    links:
      - proxy-manager:proxy-manager
    volumes:
      - ./logs:/code/logs

  proxy-manager:
    image: gott50/proxy-manager
    environment:
      - DEBUG=False
    env_file:
      - .env/.proxy-manager.env