version: "3"
services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - pgs_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
  api:
    image: instagramtools/api
    depends_on:
      - postgres
      - manager
    links:
      - postgres:postgres
      - manager:manager
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - APP_BOT_GATEWAY=http://manager:8765
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    env_file:
      - .env/.api.env
      - .env/.mail.env
  manager:
    image: instagramtools/manager
    command: sh start.sh 8765
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - P_USER=ec2-user
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    env_file:
      - .env/.api.env
      - .env/.manager.env
      - .env/.bot-manager.env

  nginx:
    image: instagramtools/user-interface
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEBUG=off
      - APP_API_PLACEHOLDER=/api
      - APP_API_GATEWAY=http://api:8000
      - APP_BOT_PLACEHOLDER=/bot
      - APP_BOT_GATEWAY=http://manager:8765
      - PAYMENT_PLACEHOLDER=/pay
      - PAYMENT_GATEWAY=http://payment-manager:7000

    depends_on:
      - api
      - payment-manager
      - manager
    links:
      - api:api
      - payment-manager:payment-manager
      - manager:manager

  payment-manager:
    image: instagramtools/payment-manager
    depends_on:
      - postgres
      - api
    links:
      - postgres:postgres
      - api:api
    ports:
      - "7000:7000"
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    env_file:
      - .env/.payment-manager.env

  mailserver:
    image: gott50/mailserver
    ports:
      - "7070:7070"
    environment:
      - DEBUG=False
    env_file:
      - .env/.mail.env

volumes:
  pgs_data: