version: "3"
services:
  postgres:
    image: postgres:10.5-alpine
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - .env/.postgres.env
  api:
      image: instagramtools/api
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      links:
        - postgres:postgres
      environment:
        - DEBUG=False
        - DB_SERVICE=postgres
        - DB_PORT=5432
      env_file:
      - .env/.postgres.env
      - .env/.api.env
  manager:
    image: instagramtools/manager
    command: sh wait-for.sh http://api:8000/api python start.py
    depends_on:
      - postgres
      - api
      - proxy-manager
    links:
      - postgres:postgres
      - api:api
      - proxy-manager:proxy-manager
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
    env_file:
    - .env/.postgres.env
    - .env/.api.env
    - .env/.manager.env

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 128M
    ports:
      - "4444:4444"

  nginx:
    image: instagramtools/user-interface
    ports:
     - "80:80"
     - "443:443"
    environment:
     - DEBUG=off
    env_file:
     - .env/.nginx.env
    depends_on:
    - api
    links:
    - api:api

  proxy-manager:
    image: gott50/proxy-manager
    ports:
    - "60000:60000"
    environment:
    - DEBUG=False
    env_file:
    - .env/.proxy-manager.env

volumes:
  db_data:
  log_data: