version: "2"
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 128M

  web:
    command: ["sh", "./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_quickstart.py"]
    image: instagramtools/web
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - selenium
    volumes:
      - ./logs:/code/logs