version: "3"
services:
  manager:
    restart: always
    image: instagramtools/manager
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
    env_file:
    - .env/.postgres.env
    - .env/.api.env
    - .env/.manager.env
  postgres:
    restart: always
    image: postgres:10
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env/.postgres.env

  web:
    image: instagramtools/web
    command: ["./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_quickstart.py"]
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - selenium
    volumes:
      - log_data:/code/logs
  selenium:
    restart: always
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"

  nginx:
     restart: always
     image: instagramtools/user-interface
     ports:
       - "80:80"
     environment:
       - DEBUG=off
     env_file:
       - .env/.nginx.env

  api:
      restart: always
      image: instagramtools/api
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      links:
        - postgres:postgres
      environment:
        - DEBUG=False
        - DB_SERVICE=postgres
        - DB_PORT=5432
      env_file:
      - .env/.postgres.env
      - .env/.api.env

volumes:
  db_data:
  log_data: